"""make sure URL is not unique in product table

Revision ID: 5cff6fddcde2
Revises: e0fa8cf9ba9a
Create Date: 2023-10-11 18:11:09.419612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cff6fddcde2'
down_revision: Union[str, None] = 'e0fa8cf9ba9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('url', 'products', ['url'], unique=False)
    # ### end Alembic commands ###
