"""include competitor analysis column in product

Revision ID: 9a761b0c4159
Revises: 4976c6d1e98a
Create Date: 2023-10-11 20:36:30.241451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a761b0c4159'
down_revision: Union[str, None] = '4976c6d1e98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('competitor_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'competitor_analysis')
    # ### end Alembic commands ###
