"""test

Revision ID: de319184bb9e
Revises: 5cff6fddcde2
Create Date: 2023-10-11 18:17:49.155087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de319184bb9e'
down_revision: Union[str, None] = '5cff6fddcde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('url', 'products', ['url'], unique=False)
    # ### end Alembic commands ###
