"""make sure URL is not unique in product table

Revision ID: e0fa8cf9ba9a
Revises: 293b5d854388
Create Date: 2023-10-11 18:05:03.824682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fa8cf9ba9a'
down_revision: Union[str, None] = '293b5d854388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('url', 'products', ['url'], unique=False)
    # ### end Alembic commands ###
